# Generated by Django 4.1.3 on 2022-11-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='имя автора')),
                ('email', models.EmailField(max_length=254, verbose_name='почта автора')),
                ('note', models.TextField(max_length=3000, verbose_name='запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время редактирования')),
                ('status', models.CharField(choices=[('active', 'активно'), ('blocked', 'заблокировано')], default='active', max_length=30, verbose_name='статус')),
            ],
        ),
    ]
