# Generated by Django 4.1.3 on 2022-11-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='name',
            new_name='author',
        ),
    ]
